//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linkdev.MOA.POC.BLL.ResourceFiles.Common
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Linkdev.MODON.Portal.BLL.ResourceFiles.Common.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Soory, you can&apos;t add this user as he already was added before.
        /// </summary>
        public static string AddContactToContract
        {
            get
            {
                return ResourceManager.GetString("AddContactToContract", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry, you are not authorized to access this page.
        /// </summary>
        public static string AuthorizationError
        {
            get
            {
                return ResourceManager.GetString("AuthorizationError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry, you don&apos;t the permission to change that contract..
        /// </summary>
        public static string AuthrizedToUpdateContract
        {
            get
            {
                return ResourceManager.GetString("AuthrizedToUpdateContract", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry, your CR has one or more contracts with indebtedness.
        /// </summary>
        public static string CRContractsBalancesNotValid
        {
            get
            {
                return ResourceManager.GetString("CRContractsBalancesNotValid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry, selected CR doesn&apos;t detected as General or Safety..
        /// </summary>
        public static string CRHasNoCertificateType
        {
            get
            {
                return ResourceManager.GetString("CRHasNoCertificateType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry, selected CR doesn&apos;t have privileges.
        /// </summary>
        public static string CRHasNoPrivilege
        {
            get
            {
                return ResourceManager.GetString("CRHasNoPrivilege", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry, selected CR doesn&apos;t have Region.
        /// </summary>
        public static string CRHasNoRegion
        {
            get
            {
                return ResourceManager.GetString("CRHasNoRegion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email Not Confirmed.
        /// </summary>
        public static string EmailNotConfirmed
        {
            get
            {
                return ResourceManager.GetString("EmailNotConfirmed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry, something went wrong. Please try again, if the problem persists, please contact us.
        /// </summary>
        public static string Error
        {
            get
            {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}&lt;br&gt;&lt;a href=&apos;{1}&apos;&gt;{2}&lt;/a&gt;.
        /// </summary>
        public static string GenericMessage
        {
            get
            {
                return ResourceManager.GetString("GenericMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Incorrect Password.
        /// </summary>
        public static string Incorrect_Password
        {
            get
            {
                return ResourceManager.GetString("Incorrect Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string INVAILD_USER
        {
            get
            {
                return ResourceManager.GetString("INVAILD_USER", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry, you don&apos;t have enough privileges to do this action.
        /// </summary>
        public static string NotAuthorizedAction
        {
            get
            {
                return ResourceManager.GetString("NotAuthorizedAction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The password has not updated correctly.
        /// </summary>
        public static string Password_Not_Updated
        {
            get
            {
                return ResourceManager.GetString("Password_Not_Updated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry, you don&apos;t have enough privileges to rate this request.
        /// </summary>
        public static string RatingError
        {
            get
            {
                return ResourceManager.GetString("RatingError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry, but the choosen contact not related to the current Contract.
        /// </summary>
        public static string RemoveContactFromContract
        {
            get
            {
                return ResourceManager.GetString("RemoveContactFromContract", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry, system unable to find the requested service..
        /// </summary>
        public static string ServiceDetailsError
        {
            get
            {
                return ResourceManager.GetString("ServiceDetailsError", resourceCulture);
            }
        }
    }
}
