import { EntityReferenceItem } from "src/modules/shared/Models/EntityReferenceItem.model";

export class BuildingLicenseModel {
	LandArea?: string;
	ConsultingOfficeIndustrialCity?: string;
	VersionNumber?: number;
	CreatedOn?: Date;
	ldv_accountyominame?: string;
	ldv_contractnumbername?: string;
	IssuanceDateinHijri?: string;
	modifiedbyyominame?: string;
	ldv_buildinglicenserequestname?: string;
	ConstructionBudget: number;
	owneridtype?: string;
	LicenseType?: string;
	ldv_consultingofficeyominame?: string;
	CreatedByDelegate?: string;
	ConsultingOfficeMobileNumber?: string;
	modifiedbyname?: string;
	ldv_contractoryominame?: string;
	ContractorMobileNumber?: string;
	owneridname?: string;
	RecordCreatedOn?: Date;
	ldv_requestername?: string;
	ExpiryDayinHijri?: number;
	createdonbehalfbyyominame?: string;
	ModifiedByDelegate?: string;
	ExpiryDateinHijri?: string;
	OwningTeam?: string;
	ExpiryMonthinHijri?: number;
	Status?: number;
	IssuanceMonthinHijri?: number;
	TimeZoneRuleVersionNumber?: number;
	ldv_consultingofficename?: string;
	ldv_contractorindustrialcityname?: string;
	Id: string;
	BuildingCompletionPercentage?: number;
	createdonbehalfbyname?: string;
	GregorianExpiryDate?: Date;
	UTCConversionTimeZoneCode?: number;
	ldv_consultingofficeindustrialcityname?: string;
	ldv_contractorname?: string;
	Owner?: string;
	ModifiedOn?: Date;
	ImportSequenceNumber?: number;
	owneridyominame?: string;
	ContractNumber?: string;
	GregorianIssuanceDate?: Date;
	ActivityType?: number;
	FloorsNumber?: number;
	IssuanceDayinHijri?: number;
	createdbyname?: string;
	RequestStatus?: string;
	modifiedonbehalfbyname?: string;
	Requester?: string;
	ldv_requeststatusname?: string;
	IssuanceYearinHijri?: number;
	CreatedBy?: string;
	ldv_industrialcityname?: string;
	ModifiedBy?: string;
	createdbyyominame?: string;
	OwningUser?: string;
	ldv_licensetypename?: string;
	OwningBusinessUnit?: string;
	CRName?: string;
	LicenseNumber?: string;
	Location?: string;
	ldv_requesteryominame?: string;
	BuildingLicenseRequest?: string;
	ExpiryYearinHijri?: number;
	StatusReason?: number;
	modifiedonbehalfbyyominame?: string;
	ldv_accountname?: string;
	ContractorIndustrialCity?: string;
	IndustrialCity?: string;

	ConsultingOffice: EntityReferenceItem;
	ConsultingOfficeId:string;

	Contractor: EntityReferenceItem;
	ContractorId:string;
}
