//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkDev.MOA.POC.DAL.MembershipIdentityDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    public partial class MODON_IdentityMembershipEntities : DbContext
    {
        public MODON_IdentityMembershipEntities()
            : base("name=MODON_IdentityMembershipEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<UserSession> UserSessions { get; set; }
    }
}
