//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkDev.MOA.POC.DAL.MembershipIdentityDB
{
    using System;
    using System.Collections.Generic;

    public partial class UserSession
    {
        public int Id { get; set; }
        public string OwnerUserId { get; set; }
        public string AuthToken { get; set; }
        public System.DateTime ExpirationDateTime { get; set; }
    }
}
