export interface IAppConfig {
    batchProcessHost: string;
    reCaptchaSiteKey: string,
    newsDefaultImage: string,
    newsListingPageUrl: string,
    newsDetailsPageUrl: string,
    contributePageUrl: string,
    isdbReadMoreUel: string,
    faqListingPageUrl: string,
    twitterUrl: string,
    facebookUrl: string,
    youtubeUrl: string,
    paymentLink:string,
    trackOrderUrl: string,
    signUrl: string,
    contactUsEmail: string,
    newsListingPageSize: string,
    newsListName: string,
    registerUrl: string,
    forgetPasswordUrl: string,
    changePasswordUrl: string,
    homeUrl: string,
    authenticationApi: string,
    adahiApiHost: string,
    batchApiHost:string
    ApiSegments: any,
    logoutUrl: string,
    bidDetailsPageUrl:string,
    bidListingPageUrl:string,
    bidsListingPageSize:string,
    photoGalleryRoot: string,
    photoGalleryListingPageUrl: string,
    videoGalleryRoot: string,
    videoGalleryListingPageUrl: string,
    videoGalleryListingPageSize: string,
    youtubeApiKey: string,
    photoGalleryListingPageSize: string,
    orderingApi: string,
    emptyShoppingCart: string
    editProfileUrl: string,
    contactusKsaNumber:string,
    callCenterksa:string,
    contactusKsaNumber2:string,
    contactusKsaNumber3:string,
    contactusUsaNumber:string,
    contactusUKNumber:string,
    homePageUrl:string,
    orderHistoryUrl:string,
    allowedFileTypes:string,
    representativePageUrl:string
    BatchNotificationMaxCount:number;
    whatsappNumber:string;
    sellRitualPage: string;
    batchListPageUrl: string;
}